// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeqVyLxMv8u_CDilvJClr0Nducf93p4zw',
    appId: '1:1054799797495:android:d7ccc9d32692387b6a07f2',
    messagingSenderId: '1054799797495',
    projectId: 'task-management-96214',
    storageBucket: 'task-management-96214.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKt0ElLZnzKHdjc9SObbkrv6XobpEi5ek',
    appId: '1:1054799797495:ios:3841b63bf45654346a07f2',
    messagingSenderId: '1054799797495',
    projectId: 'task-management-96214',
    storageBucket: 'task-management-96214.appspot.com',
    androidClientId: '1054799797495-eqfsea2dgkfdo3cil4dfkrh78jssr81i.apps.googleusercontent.com',
    iosClientId: '1054799797495-ci363cnrb87d6absshlhs3svif9fmem9.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1lskNZ79rnce6oprNIIRE8kPtc7hVx58',
    appId: '1:1054799797495:web:6cc9963193ac5d206a07f2',
    messagingSenderId: '1054799797495',
    projectId: 'task-management-96214',
    authDomain: 'task-management-96214.firebaseapp.com',
    storageBucket: 'task-management-96214.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKt0ElLZnzKHdjc9SObbkrv6XobpEi5ek',
    appId: '1:1054799797495:ios:3841b63bf45654346a07f2',
    messagingSenderId: '1054799797495',
    projectId: 'task-management-96214',
    storageBucket: 'task-management-96214.appspot.com',
    androidClientId: '1054799797495-eqfsea2dgkfdo3cil4dfkrh78jssr81i.apps.googleusercontent.com',
    iosClientId: '1054799797495-ci363cnrb87d6absshlhs3svif9fmem9.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1lskNZ79rnce6oprNIIRE8kPtc7hVx58',
    appId: '1:1054799797495:web:fb5c9ec2f2f736306a07f2',
    messagingSenderId: '1054799797495',
    projectId: 'task-management-96214',
    authDomain: 'task-management-96214.firebaseapp.com',
    storageBucket: 'task-management-96214.appspot.com',
  );

}